### ISSUE TITLE
初始化报错 eglCreatePbufferSurface: EGL error: 0x3004

### ISSUE THREAD

**Issue by a365344743s** [AgoraIO-Community/MediaIO-Camera#11]
bugly收集到sdk初始化报错，这个是模拟器原因造成的吗，我看手机是root过的

# 设备信息
系统版本 Android 9,level 28
ROM OPPO/OPPO
CPU架构 arm64-v8a
网络APN | Wi-Fi 
是否ROOT | 是
可用内存大小 | 9.34 GB ( 160.67% )
可用存储空间 | 10.63 GB ( 85.33% )
可用SD卡大小 | 10.63 GB ( 85.33% )
ROM详情 | OPPO/OPPO/PCRT00:9/mv-dev103041042:user/release-keys/fail

# 堆栈信息
camera_channel(200)
java.lang.RuntimeException
eglCreatePbufferSurface: EGL error: 0x3004
io.agora.capture.framework.gles.core.EglCore.checkEglError(EglCore.java:387)
io.agora.capture.framework.gles.core.EglCore.createOffscreenSurface(EglCore.java:267)
io.agora.capture.framework.modules.channels.VideoChannel.initOpenGL(VideoChannel.java:94)
io.agora.capture.framework.modules.channels.VideoChannel.init(VideoChannel.java:80)
io.agora.capture.framework.modules.channels.VideoChannel.run(VideoChannel.java:73)

main(2)
java.lang.Object.wait(Native Method)
android.os.HandlerThread.getLooper(HandlerThread.java:84)
io.agora.capture.framework.modules.channels.VideoChannel.startChannel(VideoChannel.java:168)
io.agora.capture.framework.modules.channels.ChannelManager.ensureChannelRunning(ChannelManager.java:70)
io.agora.capture.video.camera.VideoModule.startChannel(VideoModule.java:64)
io.agora.capture.video.camera.CameraVideoManager.init(CameraVideoManager.java:102)
io.agora.capture.video.camera.CameraVideoManager.create(CameraVideoManager.java:65)
io.agora.capture.video.camera.CameraVideoManager.create(CameraVideoManager.java:56)
io.agora.capture.video.camera.CameraVideoManager.create(CameraVideoManager.java:52)

# 跟踪日志
08-06 23:45:49.729 8706 8870 E EGL_adreno: CreateContext rcMajorVersion:3, minorVersion:0
08-06 23:45:49.730 8706 8870 D EGL_adreno: eglCreateContext: 0x7fb2296edf80: maj 3 min 0 rcv 3
08-06 23:45:49.730 8706 8870 E EGL_adreno: [getAttribValue] Bad attribute idx
08-06 23:45:49.730 8706 8870 D EGL_adreno: eglGetConfigAttrib: bad attrib 0x3339
08-06 23:45:49.730 8706 8870 E EGL_adreno: tid 8870: eglGetConfigAttrib(1207): error 0x3004 (EGL_BAD_ATTRIBUTE)
--------- beginning of crash
08-06 23:45:49.732 8706 8870 E AndroidRuntime: FATAL EXCEPTION: camera_channel
08-06 23:45:49.732 8706 8870 E AndroidRuntime: Process: cn.chbx.moliaoplus, PID: 8706
08-06 23:45:49.732 8706 8870 E AndroidRuntime: java.lang.RuntimeException: eglCreatePbufferSurface: EGL error: 0x3004
08-06 23:45:49.732 8706 8870 E AndroidRuntime: at io.agora.capture.framework.gles.core.EglCore.checkEglError(EglCore.java:387)
08-06 23:45:49.732 8706 8870 E AndroidRuntime: at io.agora.capture.framework.gles.core.EglCore.createOffscreenSurface(EglCore.java:267)
08-06 23:45:49.732 8706 8870 E AndroidRuntime: at io.agora.capture.framework.modules.channels.VideoChannel.initOpenGL(VideoChannel.java:94)
08-06 23:45:49.732 8706 8870 E AndroidRuntime: at io.agora.capture.framework.modules.channels.VideoChannel.init(VideoChannel.java:80)
08-06 23:45:49.732 8706 8870 E AndroidRuntime: at io.agora.capture.framework.modules.channels.VideoChannel.run(VideoChannel.java:73)

**Comment by xgfd3** [comment]
看了下崩溃堆栈，问题崩在了 
https://github.com/AgoraIO-Community/MediaIO-Camera/blob/master/Android/framework/src/main/java/io/agora/capture/framework/gles/core/EglCore.java
```
int[] surfaceAttribs = {
        EGL14.EGL_WIDTH, width,
        EGL14.EGL_HEIGHT, height,
        EGL14.EGL_NONE
};
EGLSurface eglSurface = EGL14.eglCreatePbufferSurface(mEGLDisplay, mEGLConfig,
        surfaceAttribs, 0);
```
其中显示surfaceAttribs的参数有误，但是0x3339这个属性值在EGL14里并没有，可能是一些root系统独有或者是其bug。
