### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unknown camera ID

### ISSUE THREAD

**Issue by hoangchungk53qx1** [AgoraIO-Community/MediaIO-Camera#19]
Model:OnePlus 7 Pro
Description : i had a crash here, i looked for the cause, but your gallery couldn't find the camera Id
    private fun initVideoCaptureAsync() {
        Thread {
            FURenderer.getInstance().setup(applicationContext)
            mVideoManager = CameraVideoManager.create(
                applicationContext,
                PreprocessorFaceUnity(
                    applicationContext
                )
            )
        }.start()
    }

**Comment by plutoless** [comment]
do you have the full crash stack trace?

**Comment by hoangchungk53qx1** [comment]
stack trace "
android.hardware.Camera._getCameraInfo (Camera.java)
android.hardware.Camera.getCameraInfo (Camera.java:438)
com.faceunity.core.utils.CameraUtils.getCameraOrientation (CameraUtils.kt:96)
com.faceunity.nama.FURenderer$1.onSuccess (FURenderer.java:95)
com.faceunity.core.support.SDKController.setup$fu_core_release (SDKController.kt:69)
com.faceunity.core.faceunity.FURenderManager.registerFURender (FURenderManager.kt:35)
com.faceunity.nama.FURenderer.setup (FURenderer.java:89)
com.xxx.xxxx.initVideoCaptureAsync$lambda-0 (.kt:74)
com.xxx.xxxx.$r8$lambda$E00dWa-xWH7i8u6zmOqLnruxqlc (.kt)
com.xxx.xxxx$$InternalSyntheticLambda$1$784bee418450a387f8ad672a70e21d25cdf81d5dc65d5296864d8fe9f3f066fc$0.run

**Comment by xgfd3** [comment]
The crash is happened for CameraUtils.getCameraOrientation() methed calling Camera.getCameraInfo without catching the exeception. It is sorry that we can not do anything for you.
To resolving the problem, you can try to catch the exeception of Camera.getCameraInfo.

**Comment by hoangchungk53qx1** [comment]
I solved it that way. i think it is not the optimal solution , can i research and create a PR ?

**Comment by plutoless** [comment]
@hoangchungk53qx1 of course :) feel free to raise a PR when you find sth. Any contribution would be greatly appreciated.

**Comment by hoangchungk53qx1** [comment]
@xgfd3 @plutoless i noticed android camera android.hardware.camera deprecated , why not use camera2 instead, is there any plan to convert to camera2

**Comment by brianxcli** [comment]
Possible issues:
1. If it is ok when two modules are accessing camera hardware (FURenderer and camera manager); or is it ok for FURenderer to touch camera logic, what if camera manager uses a different camera to FURenderer? 
2. I'm not sure it is appropriate when FURenderer.setup and PreprocessorFaceUnity are both trying to initialize FURenderer. On  one hand the preprocessor should handle it all, and FURenderer.setup seems to do a lot more than we assume on the other.
